call_me_web_homepage:
    pattern:  /
    defaults: { _controller: CallMeWebBundle:Default:index }

register_page:
    pattern:     /register
    defaults: { _controller: CallMeWebBundle:Default:register }

process_register:
    pattern:     /process-register
    defaults: { _controller: CallMeWebBundle:Default:processRegister }

login:
    pattern: /login
    defaults: { _controller: CallMeWebBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

forgot_password:
    pattern: /forgot-password
    defaults: { _controller: CallMeWebBundle:Security:forgotPassword }

process_forgot_password:
    pattern: /process-forgot-password
    defaults: { _controller: CallMeWebBundle:Security:processForgotPassword }
    methods: [POST]

user_settings:
   pattern: /settings
   defaults: { _controller: CallMeWebBundle:User:settings }
   methods: [GET]

process_user_settings:
   pattern: /process-user-settings
   defaults: { _controller: CallMeWebBundle:User:processSettings }
   methods: [POST]